import { nunitoSans, workSans } from "@/fonts";
import "../globals.css";
import ClientSidebar from "@/components/Sidebar/ClientSidebar";

export const metadata = {
    title: "Dashboard",
    description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`bg-dashboard text-white ${workSans.className} antialiased`}>
                <div className="min-h-screen p-8 h-screen">
                    <div className="flex md:flex-row gap-10 h-full w-full">
                        <ClientSidebar />
                        {children}
                    </div>
                </div>
            </body>
        </html>
    );
}
