import "../globals.css";
import { nunitoSans, workSans } from "@/fonts";
import HomeNav from "@/components/Navbar/HomeNav";
import HomeFooter from "@/components/HomeFooter";

export const metadata = {
    title: "QuickCopy AI",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${workSans.className} antialiased`}>
                <HomeNav />
                {children}
                <HomeFooter />
            </body>
        </html>
    );
}
