import AuthNav from "@/components/Navbar/AuthNav";
import "../globals.css";
import { nunitoSans, workSans } from "@/fonts";

export const metadata = {
    title: "QuickCopy AI",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <head>
                <link rel="icon" href="/sm-logo.ico" sizes="any" />
            </head>
            <body className={`${workSans.className}  antialiased bg-auth overflow-y-hidden`}>
                <AuthNav />
                {children}
            </body>
        </html>
    );
}
